server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: postgres
    username: root
    password: root
    host: 127.0.0.1
    port: 5432
    db_name: app_local
    max_idle_conns: 10
    max_open_conns: 100
    conn_max_lifetime: 3600s
    conn_max_idle_time: 3600s
  redis:
    addr: 127.0.0.1:6379
    dial_timeout: 1s
    read_timeout: 1s
    write_timeout: 1s

kafka:
  brokers: "127.0.0.1:9092"
  group_id: "app-svc"
  write_timeout: 10s
  read_timeout: 10s
