x-image: &image
  image: xxx/app-service:v1.0.1-dev
  platform: linux/amd64

services:
  app-service:
    <<: *image
    network_mode: "host"
    container_name: wallet-service
    command: ["wallet-service", "-conf", "/app/config/wallet-service-config.yaml"]
    volumes:
      - ./wallet-service-config.yaml:/app/config/wallet-service-config.yaml:ro
      - ./init_data.sql:/app/config/init_data.sql:ro
      - /home/user_00/mpc-wallet/certs:/app/config/certs:ro
      - /home/user_00/mpc-wallet/keys:/app/config/keys:ro
      - ./caller-config.json:/app/config/caller-config.json:ro
      - ./clientkey.json:/app/config/clientkey.json:ro
      - ./PrivateKmsCA_kst-hkk69719ad00mouuxp0c9.pem:/app/config/PrivateKmsCA_kst-hkk69719ad00mouuxp0c9.pem:ro
    environment:
      - LOG_LEVEL=info
      - NACOS_SERVER_ADDRS=mse-a25885c14-nacos-ans.mse.aliyuncs.com:8848
      - NACOS_NAMESPACE_ID=xfin_nacos_dev
    restart: unless-stopped
