services:
  app-service:
    build:
      context: ../../
      dockerfile: deploy/local/Dockerfile
    container_name: kratos-app-service
    network_mode: "host"
    command: ["server", "-conf", "/app/config/app-service-config.yaml"]
    volumes:
      - ./app-service-config.yaml:/app/config/app-service-config.yaml:ro
    environment:
      - LOG_LEVEL=info
      - NACOS_SERVER_ADDRS=127.0.0.1:8848
    restart: unless-stopped
