// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos-layout/internal/conf"
	"github.com/go-kratos/kratos-layout/internal/job"
	"github.com/go-kratos/kratos-layout/internal/server"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"

	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func wireApp(confServer *conf.Server, arg []*conf.CronTask, logger log.Logger) (*kratos.App, func(), error) {
	helloworldJob := job.NewHelloworldJob(logger)
	v := job.NewCronJobs(helloworldJob)
	cronServer := job.NewCronServer(arg, v, logger)
	httpServer := server.NewJobHTTPServer(confServer, logger)
	app := newApp(logger, cronServer, httpServer)
	return app, func() {
	}, nil
}
