// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos-layout/internal/conf"
	"github.com/go-kratos/kratos-layout/internal/job"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func wireApp(arg []*conf.CronTask, logger log.Logger) (*kratos.App, func(), error) {
	v := _wireValue
	cronServer := job.NewCronServer(arg, v, logger)
	app := newApp(logger, cronServer)
	return app, func() {
	}, nil
}

var (
	_wireValue = []job.CronJob(nil)
)
